### ISSUE TITLE
Piezo Frame Stream, image size

### ISSUE THREAD

**Issue by Giulia2906** [thladnik/vxPy-app#8]
It should be possible to read in frames that are not 512x512. To be able to scan in MScan a t 8Hz, the frame size needs to be reduced to 256x256. It would be convenient if the expected frame size can be easily adjusted.

**Comment by thladnik** [comment]
Both, the vxpy.extras.server.FrameReceiverTcpServer and vxpy.extras.ca_processing.RoiActivityTrackerRoutine, accept optional frame_width and frame_height arguments that can be added to the configuration YAML file. It's just that the default is set to 512x512. 

In order to use a different frame size for this, add frame_width: 256 and frame_height: 256 as additional dictionary arguments in the ROUTINES section of the configuration file for each of the routines.
